version: "3.5"

services:
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env.example
    environment:
      MYSQL_DATABASE: 'example'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    volumes:
      - mysqldata:/var/lib/mysql/

  web:
    build: .
    volumes:
      - code:/code
      - media:/media
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
        - db
volumes:
  mysqldata:
    name: mysqldatavolume
  code:
    name: codevolume
  media:
    name: mediavolume
