# Generated by Django 3.2.8 on 2021-11-11 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='название обьявления')),
                ('birthday', models.DateField(verbose_name='дата рождения щенков')),
                ('male_count', models.PositiveIntegerField(default=0, verbose_name='количество мальчиков')),
                ('female_count', models.PositiveIntegerField(default=0, verbose_name='количество девочек')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='описание щенков')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('parents_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='описание родителей')),
                ('is_transportable', models.BooleanField(default=False, verbose_name='можно отправить в другой город')),
                ('with_documents', models.BooleanField(verbose_name='наличие документов на щенков')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='цена')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'обьявление',
                'verbose_name_plural': 'обьявления',
                'db_table': 'announcement',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('name', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, verbose_name='название породы')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'породы',
                'db_table': 'breed',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='название питомника')),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='имя заводчика')),
                ('phone', models.CharField(max_length=15, verbose_name=' контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='контактный е-майл')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, upload_to='kennels/photo', verbose_name='фото заводчика')),
                ('documents', models.FileField(blank=True, upload_to='kennels/documents', verbose_name='документ / архив документов')),
                ('is_verified', models.BooleanField(default=False, verbose_name='документы подтверждены')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец (пользователь)')),
            ],
            options={
                'verbose_name': 'заводчик',
                'verbose_name_plural': 'заводчики',
                'db_table': 'kennel',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementPetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/pet_photos', verbose_name='фото щенков')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_photo', to='catalog.announcement', verbose_name='обьявление')),
            ],
            options={
                'verbose_name': 'фотография щенка',
                'verbose_name_plural': 'фотографии щенков',
                'db_table': 'announcement_pet_photo',
                'ordering': ('announcement', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementParentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/parent_photos', verbose_name='фото родителей')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_photo', to='catalog.announcement', verbose_name='обьявление')),
            ],
            options={
                'verbose_name': 'фотография родителя',
                'verbose_name_plural': 'фотографии родителей',
                'db_table': 'announcement_parent_photo',
                'ordering': ('announcement', 'id'),
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='breed',
            field=models.ForeignKey(on_delete=models.SET('Такса'), to='catalog.breed', verbose_name='порода'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='kennel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.kennel', verbose_name='заводчик'),
        ),
        migrations.CreateModel(
            name='BreedInKennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_name', to='catalog.breed', verbose_name='порода')),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.kennel', verbose_name='питомник')),
            ],
            options={
                'verbose_name': 'порода, которой занимается питомник',
                'verbose_name_plural': 'породы в питомниках',
                'db_table': 'breed_in_kennel',
                'ordering': ('kennel', 'id'),
                'unique_together': {('kennel', 'breed')},
            },
        ),
    ]
