# Generated by Django 3.2.8 on 2021-11-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.breed', verbose_name='порода'),
        ),
    ]
